version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: my_library_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_library
      MYSQL_USER: mylib_user
      MYSQL_PASSWORD: mylib_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: